---
- name: install taskwarrior
  package:
    state: latest
    name:
      - task

- name: configure task (Fedora only)
  become_user: "{{ target_user }}"
  when: ansible_distribution == 'Fedora'
  file: force=yes src={{ git_conf_dir }}/taskwarrior/taskrc.fedora dest={{ user_home_dir }}/.taskrc state=link

- name: configure task (Enterprise Linux only)
  become_user: "{{ target_user }}"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  file: force=yes src={{ git_conf_dir }}/taskwarrior/taskrc.rhel dest={{ user_home_dir }}/.taskrc state=link
