---
# dunst: Simple and configurable notification-daemon

- name: install/upgrade dunst
  package:
    state: latest
    name: dunst

- name: create dunst user config directories
  file:
    state: directory
    path: "{{ user_home_dir }}/.config/dunst"
    group: "{{ target_user }}"
    owner: "{{ target_user }}"

- name: copy dunstrc
  copy:
    src: "{{ role_path }}/files/dunstrc"
    dest: "{{ user_home_dir }}/.config/dunst/dunstrc"
    group: "{{ target_user }}"
    owner: "{{ target_user }}"
