---
- name: create bash_completion.d directory
  become_user: "{{ target_user }}"
  file:
    state: directory
    path: "{{ user_home_dir }}/.bash_completion.d"

- name: configure bash
  become_user: "{{ target_user }}"
  file:
    force: yes
    state: link
    src: "{{ git_conf_dir }}/bash/{{ item }}"
    dest: "{{ user_home_dir }}/.{{ item }}"
  with_items:
    - bashrc
    - bash_profile

- name: add Taskwarrior bash auto-completion script
  become_user: "{{ target_user }}"
  file:
    force: yes
    state: link
    src: "{{ git_conf_dir }}/taskwarrior/task.sh"
    dest: "{{ user_home_dir }}/.bash_completion.d/task.sh"
