---
- name: install npm
  package:
    state: latest
    name:
      - npm

- name: create npm local package cache directory
  become_user: "{{ target_user }}"
  file: path={{ user_home_dir }}/.npm-global state=directory

- name: configure npm
  become_user: "{{ target_user }}"
  file: force=yes src={{ git_conf_dir }}/npm/npmrc dest={{ user_home_dir }}/.npmrc state=link
