---
- name: create SSH config directories for target user
  file:
    state: directory
    path: "{{ user_home_dir }}/.ssh"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0700

- name: add SSH public key to authorized_keys
  template: 
    src: authorized_keys
    dest: "{{ user_home_dir }}/.ssh/authorized_keys"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0400

- name: configure SSH
  become_user: "{{ target_user }}"
  file:
    force: yes
    state: link
    src: "{{ git_conf_dir }}/ssh/config"
    dest: "{{ user_home_dir }}/.ssh/config"
