---
- name: create SSH config directories for target user
  file:
    state: directory
    path: "{{ user_home_dir }}/.ssh"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0700

- name: configure SSH for target user (~/.ssh/config)
  become_user: "{{ target_user }}"
  file:
    force: yes
    state: link
    src: "{{ git_conf_dir }}/ssh/config"
    dest: "{{ user_home_dir }}/.ssh/config"
