---
- name: install taskwarrior
  package:
    state: latest
    name:
      - task

- name: add taskrc (Fedora only)
  when: ansible_distribution == 'Fedora'
  copy:
    src: "{{ role_path }}/files/taskrc.fedora"
    dest: "{{ user_home_dir }}/.taskrc"
    group: "{{ target_user }}"
    owner: "{{ target_user }}"

- name: add taskrc (Enterprise Linux only)
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  template:
    src: "{{ role_path }}/files/taskrc.rhel"
    dest: "{{ user_home_dir }}/.taskrc"
    group: "{{ target_user }}"
    owner: "{{ target_user }}"
