---
- name: set up Justin's preferred Fedora Workstation configuration
  hosts: desktop
  become: yes

  roles:
    - system/base
    - system/fedora-workstation
    - apps/base
    - apps/bash
    - apps/dunst
    - apps/git
    - apps/i3wm
    - apps/minecraft
    - apps/npm
    - apps/powerline-go
    - apps/ssh
    - apps/task
    - apps/bugwarrior  # intentionally after taskwarrior role
    - apps/tmux
    - apps/vim
