---
- name: add EPEL and IUS repositories
  package:
    state: latest
    name:
      - epel-release
      - https://rhel7.iuscommunity.org/ius-release.rpm

- name: install base packages
  package:
    state: latest
    name:
      - firewalld
      - git
      - golang
      - htop
      - jq
      - pandoc
      - podman
      - python-flake8
      - python36u
      - python36u-pip
      - smartmontools
      - strace
      - which

- name: remove unused user Python packages
  become_user: "{{ target_user }}"
  pip:
    executable: pip3.6
    state: absent
    name:
      - powerline-status

- name: install user Python packages
  become_user: "{{ target_user }}"
  pip:
    executable: pip3.6
    state: latest
    extra_args: --user
    name:
      - pipenv

- name: start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
  ignore_errors: yes
