---
- name: download and extract Minecraft launcher
  unarchive:
    creates: "/usr/local/games/minecraft/"
    dest: "/usr/local/games/"
    remote_src: yes
    src: https://launcher.mojang.com/download/Minecraft.tar.gz

- name: (hack) rename Minecraft launcher directory for consistency
  command: "mv /usr/local/games/minecraft-launcher-2.1.1431/ /usr/local/games/minecraft/"
  args:
    creates: "/usr/local/games/minecraft/"

- name: copy desktop entry
  copy:
    src: "{{ role_path }}/files/minecraft.desktop"
    dest: "/usr/local/share/applications/minecraft.desktop"
