---
- name: add negativo17 fedora-flash-plugin repository
  command:
    cmd: dnf config-manager --add-repo=https://negativo17.org/repos/fedora-flash-plugin.repo
    creates: /etc/yum.repos.d/fedora-flash-plugin.repo

- name: install/upgrade flash-plugin
  package:
    name: flash-plugin
    state: latest

- name: set SELinux boolean to false for Firefox and Flash
  seboolean:
    name: unconfined_mozilla_plugin_transition
    state: no
    persistent: yes
