---
- name: install default flatpaks as user-managed flatpaks
  flatpak:
    name: "{{ item }}"
    state: present
    method: system
  loop:
    - com.bluejeans.BlueJeans
    - im.riot.Riot
    - org.signal.Signal
    - us.zoom.Zoom
