---
# dunst: Simple and configurable notification-daemon

- name: install dunst
  package:
    state: latest
    name:
      - dunst

- name: create dunst config directories
  become_user: "{{ target_user }}"
  file:
    state: directory
    path: "{{ user_home_dir }}/.config/dunst"

- name: configure dunst
  become_user: "{{ target_user }}"
  file:
    force: yes
    state: link
    src: "{{ git_conf_dir }}/dunst/dunstrc"
    dest: "{{ user_home_dir }}/.config/dunst/dunstrc"
