---
- name: import third-party repository signing keys
  rpm_key: key={{ item }} state=present
  with_items:
    - https://download.sublimetext.com/sublimehq-rpm-pub.gpg
    - https://negativo17.org/repos/RPM-GPG-KEY-slaanesh

- name: add EPEL and IUS repositories
  package:
    state: present
    name:
      - epel-release
      - https://rhel7.iuscommunity.org/ius-release.rpm

- name: add other third-party repositories
  command: yum-config-manager --add-repo {{ item }}
  with_items:
    - https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
    - https://negativo17.org/repos/epel-flash-plugin.repo
    - https://negativo17.org/repos/epel-spotify.repo
  args:
    warn: no

- name: install base packages
  ### Package notes ###
  # jpegoptim: Utility to optimize JPEG files
  # meld: Visual diff and merge tool
  # network-manager-applet: Network control / status applet for NetworkManager
  package:
    state: latest
    name:
      - ansible
      # - ansible-python3
      # - arandr
      - brasero
      - brasero-nautilus
      - docker
      # - feh
      # - ffmpeg
      # - flash-plugin
      - git
      # - gnome-shell-extension-pomodoro
      - gobby05
      - golang
      - google-roboto-slab-fonts
      # - gstreamer-ffmpeg
      # - gstreamer1-plugins-bad-free-extras
      # - gstreamer1-plugins-bad-nonfree
      # - gstreamer1-plugins-ugly
      - hexchat
      - htop
      - inkscape
      - jpegoptim
      - jq
      - libvirt
      - libvirt-devel
      - meld
      # - mpv
      - network-manager-applet
      - overpass-fonts
      # - overpass-mono-fonts
      - pandoc
      - pass
      - pavucontrol
      - picard
      - pulseaudio-utils
      - python-flake8
      - python36u
      - python36u-pip
      - ripright
      - smartmontools
      - spotify-client
      - strace
      - sublime-text
      # - thunderbird
      # - thunderbird-enigmail
      - typetype-molot-fonts
      # - vagrant
      - which
      - xclip

- name: install python packages (currently pipenv only)
  become_user: "{{ target_user }}"
  pip:
    executable: pip3.6
    state: latest
    extra_args: --user
    name:
      - pipenv

- name: start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
