---
- name: create user bash_completion.d directory
  file:
    state: directory
    path: "{{ user_home_dir }}/.bash_completion.d"
    group: "{{ target_user }}"
    owner: "{{ target_user }}"

- name: copy bashrc and bash_profile
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ user_home_dir }}/.{{ item }}"
    group: "{{ target_user }}"
    owner: "{{ target_user }}"
  loop:
    - bashrc
    - bash_profile

- name: copy user Bash auto-completion scripts
  copy:
    src: "{{ role_path }}/files/task.sh"
    dest: "{{ user_home_dir }}/.bash_completion.d/{{ item }}"
    group: "{{ target_user }}"
    owner: "{{ target_user }}"
    mode: 0775
  loop:
    - poetry.bash-completion
    - task.bash-completion
