---
- name: create user bash_completion.d directory
  file:
    state: directory
    path: "{{ user_home_dir }}/.bash_completion.d"
    group: "{{ target_user }}"
    owner: "{{ target_user }}"

- name: add user bashrc and bash_profile
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ user_home_dir }}/.{{ item }}"
    group: "{{ target_user }}"
    owner: "{{ target_user }}"
  with_items:
    - bashrc
    - bash_profile

- name: add Taskwarrior user Bash auto-completion script
  copy:
    src: "{{ role_path }}/files/task.sh"
    dest: "{{ user_home_dir }}/.bash_completion.d/task.sh"
    group: "{{ target_user }}"
    owner: "{{ target_user }}"
    mode: 0775
